


## AGI vs. Personal Income Components


```{r}
#| label: piagi-growth-plot
#| output: false
#| fig-width: 18
#| fig-height: 10

pdata |>
  mutate(variable = factor(variable, levels = c("nyspi", "nysagi"))) |>
  ggplot(aes(year, pchya, colour = variable)) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 0) +
  scale_color_manual(
    values = c("nysagi" = "#0072B2", "nyspi" = "#009E73"), #  "#E69F00"
    labels = c("nysagi" = "Adjusted Gross Income", "nyspi" = "Personal Income")
  ) +
  scale_y_continuous(
    name = "% change",
    breaks = seq(-0.1, 0.2, 0.02),
    labels = scales::label_percent(accuracy = 0.1)
  ) +
  scale_x_continuous(name = NULL, breaks = 2015:2024) +
  ggtitle("New York State Personal Income and AGI Growth Rates") +
  labs(caption = "Sources: BEA and NYS Department of Taxation and Finance") +
  theme_presentation() +
  theme(
    legend.title = element_blank(),
    legend.position = c(0.85, 0.85),
    legend.background = element_rect(fill = "white", color = "gray80"),
    legend.key.size = unit(1.5, "lines")
  )

```

```{r}
#| label: get-agi-components

# nysagi
# nyspi
# wages, interest, dividends, capgains, caploss, rrpetgain, rrpetloss, busfarmgain, bus

agi_components <- nysagi |>
  filter(
    rstat == "All Filers",
    por == "All Places",
    county == "All Places",
    state == "All",
    country == "All"
  ) |>
  filter(sortincome == 16) |>
  select(
    year,
    numret,
    nysagi,
    wages,
    interest,
    dividends,
    capgains,
    caploss,
    rrpetgain,
    rrpetloss,
    busfarmgain,
    busfarmloss,
    pensions,
    otherinc
  ) |>
  arrange(year)

agibase <- agi_components |>
  mutate(
    intdiv = interest + dividends,
    capnet = capgains - caploss,
    rrpetnet = rrpetgain - rrpetloss,
    busfarmnet = busfarmgain - busfarmloss,
    allother = nysagi -
      wages -
      intdiv -
      capnet -
      rrpetnet -
      busfarmnet -
      pensions -
      otherinc
  ) |>
  select(
    year,
    nysagi,
    wages,
    intdiv,
    capnet,
    rrpetnet,
    busfarmnet,
    pensions,
    otherinc,
    allother
  ) |>
  arrange(year)

agibase2 <- agibase |>
  mutate(other = nysagi - wages - capnet) |>
  select(year, nysagi, wages, capnet, other)

# combine agi components plus nyspi
piagi <- agibase2 |>
  pivot_longer(cols = -year, names_to = "variable", values_to = "value") |>
  bind_rows(pibase)

```

```{r}
#| label: show-pi-agi-components
#| output: false
#| eval: false
#| fig-width: 18
#| fig-height: 10

vars <- c("nyspi", "nysagi", "wages", "capnet")
var_labels <- c(
  "nyspi" = "Personal Income",
  "nysagi" = "Adjusted Gross Income",
  "wages" = "Wages & Salaries",
  "capnet" = "Net Capital Gains"
)
var_colors <- c(
  "nyspi" = "#009E73", # green
  "nysagi" = "#0072B2", # blue
  "wages" = "#E69F00", # orange
  "capnet" = "#D55E00" # red
)

piagi |>
  filter(variable != "other") |>
  arrange(variable, year) |>
  mutate(
    pchya = value / lag(value) - 1,
    .by = variable,
    variable = factor(variable, levels = vars)
  ) |>
  filter(!is.na(pchya)) |>
  ggplot(aes(year, pchya, colour = variable)) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 0) +
  scale_color_manual(
    values = var_colors,
    labels = var_labels
  ) +
  scale_y_continuous(
    name = "% change",
    breaks = seq(-0.6, 0.6, 0.1),
    labels = scales::label_percent(accuracy = 1)
  ) +
  scale_x_continuous(name = NULL, breaks = 2015:2024) +
  ggtitle("Growth Rates of Personal Income, AGI, and Major Components") +
  labs(caption = "Sources: BEA and NYS Department of Taxation and Finance") +
  theme_presentation() +
  theme(
    legend.title = element_blank(),
    legend.position = c(0.85, 0.85), # upper left to avoid data
    legend.background = element_rect(fill = "white", color = "gray80"),
    legend.key.size = unit(1.5, "lines")
  )
```

```{r}
#| label: show-pi-agi-components2
#| output: false
#| eval: false
#| fig-width: 18
#| fig-height: 10

vars <- c("nyspi", "nysagi", "wages", "capnet", "other")
var_labels <- c(
  "nyspi" = "Personal Income",
  "nysagi" = "Adjusted Gross Income",
  "wages" = "Wages & Salaries",
  "capnet" = "Net Capital Gains",
  "other" = "Other AGI Components"
)
var_colors <- c(
  "nyspi" = "#009E73", # green
  "nysagi" = "#0072B2", # blue
  "wages" = "#E69F00", # orange
  "capnet" = "#D55E00", # red
  "other" = "gray50"
)

piagi |>
  # filter(variable != "other") |>
  arrange(variable, year) |>
  mutate(
    pchya = value / lag(value) - 1,
    .by = variable,
    variable = factor(variable, levels = vars)
  ) |>
  filter(!is.na(pchya)) |>
  ggplot(aes(year, pchya, colour = variable)) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 0) +
  scale_color_manual(
    values = var_colors,
    labels = var_labels
  ) +
  scale_y_continuous(
    name = "% change",
    breaks = seq(-0.6, 0.6, 0.1),
    labels = scales::label_percent(accuracy = 1)
  ) +
  scale_x_continuous(name = NULL, breaks = 2015:2024) +
  ggtitle("Growth Rates of Personal Income, AGI, and Major Components") +
  labs(caption = "Sources: BEA and NYS Department of Taxation and Finance") +
  theme_presentation() +
  theme(
    legend.title = element_blank(),
    legend.position = c(0.85, 0.85), # upper left to avoid data
    legend.background = element_rect(fill = "white", color = "gray80"),
    legend.key.size = unit(1.5, "lines")
  )

```

```{r}
#| label: show-pi-agi-components3
#| output: true
#| fig-width: 18
#| fig-height: 10

vars <- c("nyspi", "nysagi", "wages", "capnet")
var_labels <- c(
  "nyspi" = "Personal Income",
  "nysagi" = "Adjusted Gross Income",
  "wages" = "Wages & Salaries",
  "capnet" = "Net Capital Gains"
)
var_colors <- c(
  "nyspi" = "#009E73", # green
  "nysagi" = "#0072B2", # blue
  "wages" = "#E69F00", # orange
  "capnet" = "#D55E00" # red
)
var_linewidths <- c(
  "nyspi" = 2,
  "nysagi" = 2,
  "wages" = 1,
  "capnet" = 1
)

piagi |>
  filter(variable != "other") |>
  arrange(variable, year) |>
  mutate(
    pchya = value / lag(value) - 1,
    .by = variable,
    variable = factor(variable, levels = vars)
  ) |>
  filter(!is.na(pchya)) |>
  ggplot(aes(year, pchya, colour = variable)) +
  geom_line(aes(linewidth = variable)) +
  geom_point() +
  geom_hline(yintercept = 0) +
  scale_color_manual(
    values = var_colors,
    labels = var_labels
  ) +
  scale_linewidth_manual(
    values = var_linewidths,
    guide = "none" # hide linewidth from legend
  ) +
  scale_y_continuous(
    name = "% change",
    breaks = seq(-0.6, 0.6, 0.1),
    labels = scales::label_percent(accuracy = 1)
  ) +
  scale_x_continuous(name = NULL, breaks = 2015:2024) +
  ggtitle(
    "Growth Rates of Personal Income, AGI, and Major Components"
  ) +
  labs(caption = "Sources: BEA and NYS Department of Taxation and Finance") +
  theme_presentation() +
  theme(
    legend.title = element_blank(),
    legend.position = c(0.85, 0.85),
    legend.background = element_rect(fill = "white", color = "gray80"),
    legend.key.size = unit(1.5, "lines")
  )

```


```{=html}
<!-- - PI includes all residents. AGI includes resident *tax filers* and non-resident *tax filers*
- PI includes employer contributions for benefits such as health insurance and pensions, AGI does not
- PI includes the value of certain benefits such as the value of Medicare and Medicaid benefits, but AGI does not
- PI does NOT include accrued or realized capital gains, but AGI includes realized gains
- ...and more... -->
```